#cloud-config
# More info - https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/
# Validate YAML: http://yamllint.com/
# Install command: coreos-install -C stable -c simple.txt -d /dev/sda

users:
  - name: core
    passwd: $1$XMZXIbkN$WKmZMCgi5pQWXb7jSywjp1
coreos: 
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    # discovery: https://discovery.etcd.io/fe7d7d5ba73754a9170f121f580bf3fc
    # WARNING: replace each time you 'vagrant destroy'
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=fleet

        [Service]
        Environment=FLEET_PUBLIC_IP=$public_ipv4
        ExecStart=/usr/bin/fleet
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
    - name: blocker.service
      command: start
      content: |
        [Unit]
        After=network-online.target        
        Before=proxy.service
        Description=Blocker Service
        Documentation=http://github.com/infratablewoman/blocker
        Requires=network-online.target

        [Service]
        TimeoutStartSec=10m
        ExecStartPre=-/usr/bin/docker kill blocker1
        ExecStartPre=-/usr/bin/docker rm blocker1
        ExecStartPre=-/usr/bin/mkdir /tmp/blocks
        ExecStart=/usr/bin/docker run --publish 6045:8002 --name blocker1 -v /tmp:/tmp inflatablewoman/blocker 
        RemainAfterExit=yes
  update: 
    group: alpha
    reboot-strategy: reboot